### ISSUE TITLE
L pip is not working

### ISSUE THREAD

**Issue by Rabeata** [lfabreges/nativescript-localize#22]
## I add {{ 'INJAZ4U' | L }} this in HTML
and L pip is not working

and I add import { NativeScriptLocalizeModule } from "nativescript-localize/angular"; in shared NgModule and add it in exports 

`The pipe 'L' could not be found ("
JS:         ios.position="left">
JS:     </ActionItem>
JS:     <Label class="action-bar-title" tex[ERROR ->]t="{{ 'INJAZ4U' | L }}"></Label>
JS: </ActionBar>
JS:
JS: "): ng:///data/data/org.nativescript.ElectionsApp/files/app/Components/voters/voters.component.html@11:39
JS: Error: Template parse errors:
JS: The pipe 'L' could not be found ("
JS:         ios.position="left">
JS:     </ActionItem>
JS:     <Label class="action-bar-title" tex[ERROR ->]t="{{ 'INJAZ4U' | L }}"></Label>
JS: </ActionBar>
JS:
JS: "): ng:///data/data/org.nativescript.ElectionsApp/files/app/Components/voters/voters.component.html@11:39
JS:     at syntaxError (file:///data/data/org.nativescript.ElectionsApp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:528:34) [angular]
JS:     at TemplateParser.parse (file:///data/data/org.nativescript.ElectionsApp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:24710:19) [angular]
JS:     at JitCompiler._parseTemplate (file:///data/data/org.nativescript.ElectionsApp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:34663:37) [angular]
JS:     at JitCompiler._compileTemplate (file:///data/data/org.nativescript.ElectionsApp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:34638:23) [angular]
JS:     at file:///data/data/org.nativescript.ElectionsApp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:34539:62 [angular]
JS:     at Set.forEach (native) [angular]
JS:     at JitCompiler._compileComponents (file:///data/data/org.nativescript.ElectionsApp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:34539:19) [angular]
JS:     at file:///data/data/org.nativescript.ElectionsApp/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:34409:19 [angular]
JS:     at Object.onInvoke (file:///data/data/org.nativescript.ElectionsApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:4772:33) [angular]`

**Comment by Rabeata** [comment]
Solved ....
Just i import NativeScriptCommonModule in the NgModule for each component 
:)
